# https://github.com/getnf/getnf

function __get_nf_cmp_str
    printf %b\n "
0xProto\\t'1) 0xProto'              
3270\\t'2) 3270'                 
Agave\\t'3) Agave'                
AnonymousPro\\t'4) AnonymousPro'         
Arimo\\t'5) Arimo'                
AurulentSansMono\\t'6) AurulentSansMono'     
BigBlueTerminal\\t'7) BigBlueTerminal'      
BitstreamVeraSansMon\\t'8) BitstreamVeraSansMon' 
CascadiaMono\\t'9) CascadiaMono'         
CodeNewRoman\\t'10) CodeNewRoman'        
ComicShannsMono\\t'11) ComicShannsMono'     
CommitMono\\t'12) CommitMono'          
Cousine\\t'13) Cousine'             
D2Coding\\t'14) D2Coding'            
DaddyTimeMono\\t'15) DaddyTimeMono'       
DejaVuSansMono\\t'16) DejaVuSansMono'      
DroidSansMono\\t'17) DroidSansMono'       
EnvyCodeR\\t'18) EnvyCodeR'           
FantasqueSansMono\\t'19) FantasqueSansMono'   
FiraCode\\t'20) FiraCode'            
FiraMono\\t'21) FiraMono'            
GeistMono\\t'22) GeistMono'           
Go-Mono\\t'23) Go-Mono'            
Gohu\\t'24) Gohu'               
Hasklig\\t'25) Hasklig'            
HeavyData\\t'26) HeavyData'          
Hermit\\t'27) Hermit'             
IBMPlexMono\\t'28) IBMPlexMono'        
Inconsolata\\t'29) Inconsolata'        
InconsolataGo\\t'30) InconsolataGo'      
InconsolataLGC\\t'31) InconsolataLGC'     
IntelOneMono\\t'32) IntelOneMono'       
Iosevka\\t'33) Iosevka'            
IosevkaTerm\\t'34) IosevkaTerm'        
IosevkaTermSlab\\t'35) IosevkaTermSlab'    
JetBrainsMono\\t'36) JetBrainsMono'      
Lekton\\t'37) Lekton'             
LiberationMono\\t'38) LiberationMono'     
Lilex\\t'39) Lilex'              
MPlus\\t'40) MPlus'              
MartianMono\\t'41) MartianMono'        
Meslo\\t'42) Meslo'              
Monaspace\\t'43) Monaspace'          
Monofur\\t'44) Monofur'            
Monoid\\t'45) Monoid'         
Mononoki\\t'46) Mononoki'       
Noto\\t'47) Noto'           
OpenDyslexic\\t'48) OpenDyslexic'   
Overpass\\t'49) Overpass'       
ProFont\\t'50) ProFont'        
ProggyClean\\t'51) ProggyClean'    
Recursive\\t'52) Recursive'      
RobotoMono\\t'53) RobotoMono'     
ShareTechMono\\t'54) ShareTechMono'  
SourceCodePro\\t'55) SourceCodePro'  
SpaceMono\\t'56) SpaceMono'      
Terminus\\t'57) Terminus'       
Tinos\\t'58) Tinos'          
Ubuntu\\t'59) Ubuntu'         
UbuntuMono\\t'60) UbuntuMono'     
UbuntuSans\\t'61) UbuntuSans'     
VictorMono\\t'62) VictorMono'     
ZedMono\\t'63) ZedMono'        
iA-Writer\\t'64) iA-Writer'"
end

complete -c getnf -f
complete -c getnf -s h -d 'display this help message'
complete -c getnf -s k -d 'keep the downloaded font archives'
complete -c getnf -s a -d 'show already installed fonts in the menu'
complete -c getnf -s g -d 'Install/Uninstall/List/Update Nerd Fonts for all users'
complete -c getnf -s l -d 'show the list of installed fonts'
complete -c getnf -s i -d 'directly install the specified fonts' -xa '(__get_nf_cmp_str)'
complete -c getnf -s u -d 'uninstall the specified fonts' -xa '(__get_nf_cmp_str)'
complete -c getnf -s U -d 'update all installed NerdFonts'
complete -c getnf -s V -d 'display current getnf version'
